### ISSUE TITLE
`--recursive` only finds sub packages in `/packages/**`

### ISSUE THREAD

**Issue by chrisspiegl** [antfu/bumpp#18]
### Describe the bug

The `bumpp` package in the latest version  does not find recursive `package.json` files if they are anywhere else but the `/packages/**` folder structure.

This is despite those other folders being present in the `pnpm-workspace.yaml` file.

In the reproduction:

- running `pnpm install`
- and then running `pnpm release` in the root directory
- result: the upgrade shows that the versions in `package.json, package/app/package.json` will be updated
- however, it does not update the version in the `app/package.json`
- the `pnpm-workspace.yaml` does have the `app` directory listed as a workspace directory but not the `packages` folder!

<details>
<summary>Folder Structure</summary>

<img width="379" alt="Xnapper-2023-10-18-23 05 01" src="https://github.com/antfu/bumpp/assets/1096384/320a8d43-a43b-466c-89f1-70d6be6bfdfd">
</details>

<details>
<summary>Output of `pnpm release` => `pnpm bumpp -r`</summary>

<img width="684" alt="Xnapper-2023-10-18-23 04 43" src="https://github.com/antfu/bumpp/assets/1096384/28f81e2d-192c-4c15-abcd-453808fbf769">
</details>

### Reproduction

https://codesandbox.io/p/sandbox/reproduction-bumpp-no-recursive-grl7gm

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 21.90 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/Library/pnpm/node
    npm: 10.2.0 - ~/Library/pnpm/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 118.1.59.117
    Chrome: 118.0.5993.70
    Edge: 118.0.2088.46
    Safari: 17.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jannchie** [comment]
I'm having this problem too, and I think I'll write a pr to fix it.

**Comment by mesqueeb** [comment]
@Jannchie is your fix only for pnpm? I have an npm workspace with packages that are not under a directory called `packages` and bumpp isn't finding them with just `--recursive` it seems...
