### ISSUE TITLE
bumpp cli doesn't respect args

### ISSUE THREAD

**Issue by SukkaW** [antfu/bumpp#31]
### Describe the bug

**Reproduction**

```sh
cd /tmp
mkdir -p bumpp-repro
cd bumpp-repro
git init
npm init -y
npx bumpp -r --all --commit=\"release: %s\" --tag=\"%s\" --no-push
```

**Expect**

Git tag name should not have the prefix `v`

**Actual**

```sh
git tag

v1.0.1
(END)
```

----

cc @Bernankez for #20.

### Reproduction

See above

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 217.36 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/Library/Caches/fnm_multishells/95167_1713107646834/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/95167_1713107646834/bin/yarn
    npm: 9.9.2 - ~/Library/Caches/fnm_multishells/95167_1713107646834/bin/npm
    pnpm: 8.15.6 - ~/Library/Caches/fnm_multishells/95167_1713107646834/bin/pnpm
    bun: 1.1.3 - ~/.npm-global/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Bernankez** [comment]
Thanks! `--tag="xxx"` should also be a valid parameter format and I missed that point. I'll make a PR to fix it later.
